version: '3'

services:
  RatingService:
    build: ./RatingService/
    restart: always
    depends_on:
      - mysql

  CommunicationService:
    build: ./CommunicationService/
    ports:
      - 8080:8080
    restart: always

  RidesharingService:
    build: ./RidesharingService/
    restart: always
    depends_on:
      - communication

  nginx:
    build: ./nginx/
    ports:
      - 10000:80
    depends_on:
      - RatingService
      - RidesharingService

  mongodb:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - my-db:/var/lib/mysql

volumes:
    my-db: