version: '3'

services:
  ratingservice:
    build: ./MyRatingService/
    restart: always
    depends_on:
      - mysql

  communicationservice:
    build: ./CommunicationService/
    ports:
      - 8085:8020
    restart: always

  ridesharingservice:
    build: ./RidesharingService/
    restart: always
    depends_on:
      - communicationservice

  nginx:
    build: ./nginx/
    ports:
      - 8080:80
    depends_on:
      - ratingservice
      - ridesharingservice

  mysql:
    container_name: mysql_db
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=Rideshare
      - MYSQL_USER=admin
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root

    volumes:
      - ./Database/mysqldb:/var/lib/mysql
      - ./Database/initdb:/docker-entrypoint-initdb.d/:ro

